
version: '3'

services:

  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    container_name: nest-app
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app